apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: http2-uploadserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http2-uploadserver
  template:
    metadata:
      labels:
        app: http2-uploadserver
    spec:
      containers:
        - name: http2-uploadserver
          image: jsenon/http2-uploadserver:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: "200m"
          command:
            - /http2-uploadserver
          args:
            [
              "server",
              "--outputdir",
              "/datas",
              "--disabletrace",
            ]
          volumeMounts:
            - mountPath: /datas
              name: http2-uploadserver-volume
      volumes:
        - name: http2-uploadserver-volume
          emptyDir: {}
